export const APP_ROUTES = {
  HOME: "/",
  FEATURES: "/features",
  PRICING: "/pricing",
  DOCS: "/docs",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  ACCEPT_INVITE: "/accept-invite",
  ONBOARDING: "/onboarding",
  DASHBOARD: "/dashboard",
  DASHBOARD_DOMAINS: "/dashboard/domains",
  DASHBOARD_CONVERSATIONS: "/dashboard/conversations",
  DASHBOARD_BILLING: "/dashboard/billing",
  DASHBOARD_BOOKINGS: "/dashboard/bookings",
  DASHBOARD_CAMPAIGNS: "/dashboard/campaigns",
  DASHBOARD_CUSTOMERS: "/dashboard/customers",
  DASHBOARD_ORDERS: "/dashboard/orders",
  DASHBOARD_INTEGRATIONS: "/dashboard/integrations",
  DASHBOARD_TEAM: "/dashboard/team",
  DASHBOARD_PRODUCTS: "/dashboard/products",
  DASHBOARD_AGENTS: "/dashboard/agents",
  DASHBOARD_KNOWLEDGE: "/dashboard/knowledge",
  DASHBOARD_ANALYTICS: "/dashboard/analytics",
  DASHBOARD_USAGE: "/dashboard/usage",
  DASHBOARD_SETTINGS: "/dashboard/settings",
} as const;
