export const APP_ROUTES = {
  HOME: "/",
  FEATURES: "/features",
  PRICING: "/pricing",
  DOCS: "/docs",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  DASHBOARD: "/dashboard",
  DASHBOARD_DOMAINS: "/dashboard/domains",
  DASHBOARD_CONVERSATIONS: "/dashboard/conversations",
  DASHBOARD_BILLING: "/dashboard/billing",
  DASHBOARD_CAMPAIGNS: "/dashboard/campaigns",
  DASHBOARD_INTEGRATIONS: "/dashboard/integrations",
  DASHBOARD_PRODUCTS: "/dashboard/products",
  DASHBOARD_AGENTS: "/dashboard/agents",
  DASHBOARD_ANALYTICS: "/dashboard/analytics",
  DASHBOARD_USAGE: "/dashboard/usage",
} as const;
